-- MySQL Script generated by MySQL Workbench
-- Sat Nov  2 00:10:16 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gadb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gadb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gadb` DEFAULT CHARACTER SET utf8 ;
USE `gadb` ;

-- -----------------------------------------------------
-- Table `gadb`.`modules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gadb`.`modules` (
  `modid` INT NOT NULL,
  `mtitle` VARCHAR(45) NULL,
  PRIMARY KEY (`modid`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `title_UNIQUE` ON `gadb`.`modules` (`mtitle` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `gadb`.`cw`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gadb`.`cw` (
  `cwid` INT NOT NULL,
  `cwtitle` VARCHAR(45) NULL,
  `modid` INT NOT NULL,
  `hidate` DATE NULL,
  `creditw` INT NULL,
  `fdd` DATE NULL,
  `status` INT NULL,
  PRIMARY KEY (`cwid`, `modid`),
  CONSTRAINT `modid`
    FOREIGN KEY ()
    REFERENCES `gadb`.`modules` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gadb`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gadb`.`students` (
  `sid` INT NOT NULL,
  `sfn` VARCHAR(45) NULL,
  `sln` VARCHAR(45) NULL,
  PRIMARY KEY (`sid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gadb`.`teachingstaff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gadb`.`teachingstaff` (
  `tsid` INT NOT NULL,
  `tsfn` VARCHAR(45) NULL,
  `tsln` VARCHAR(45) NULL,
  PRIMARY KEY (`tsid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gadb`.`scw`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gadb`.`scw` (
  `sid` INT NOT NULL,
  `cwid` INT NOT NULL,
  `tsid` INT NOT NULL,
  `md` INT NULL,
  `ma` INT NULL,
  `comments` VARCHAR(45) NULL,
  PRIMARY KEY (`sid`, `cwid`, `tsid`),
  CONSTRAINT `cwid`
    FOREIGN KEY (`cwid`)
    REFERENCES `gadb`.`cw` (`cwid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tsid`
    FOREIGN KEY (`tsid`)
    REFERENCES `gadb`.`teachingstaff` (`tsid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sid`
    FOREIGN KEY (`sid`)
    REFERENCES `gadb`.`students` (`sid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `CWID_idx` ON `gadb`.`scw` (`cwid` ASC) VISIBLE;

CREATE INDEX `TSID_idx` ON `gadb`.`scw` (`tsid` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
